FROM php:7.4-fpm as base

RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

RUN docker-php-ext-install pdo_mysql exif pcntl mbstring bcmath sockets gd
RUN addgroup www --gid 1000
RUN adduser www --uid 1000 --ingroup www --disabled-password --no-create-home --gecos ""
WORKDIR /var/www/

FROM base as build
COPY composer.json composer.lock /var/www/
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN composer update --optimize-autoloader --no-dev --ansi --no-scripts 
COPY . /var/www



FROM base as local
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
COPY --chown=www:www --from=build /var/www /var/www
COPY --from=build /usr/bin/composer /usr/bin/composer
USER www
EXPOSE 9000

FROM base as production
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
COPY --chown=www:www --from=build /var/www /var/www
USER www
EXPOSE 9000